### ISSUE TITLE
Flatpak compiles but cannot run

### ISSUE THREAD

**Issue by GrimSqueaker** [GrimSqueaker/remc2#13]
Issuing the command
```
flatpak-builder --user --install build-dir remc2.flatpak.json --force-clean
```
can build successfully but
```
flatpak run remc2.flatpak.json
```
results in an error.
I need to investigate.

**Comment by GrimSqueaker** [comment]
Hi @turican0 , Hi @thobbsinteractive ,

the Flatpak version is building and can be played now. https://github.com/GrimSqueaker/remc2/tree/feature/flatpak
This way we can bring a pre-compiled executable of remc2 to flathub and Linux users do not need to bother with compilation anymore.

A prerequisite for this was a working 64 bit build which is in good shape thanks to @turican0 .
I have based this on the current version of the merging-help branch. It would be good if we can bring this to the develop branch soon. Then I could create a PR for this Flatpak branch.

In order to make it work, I had to change how the game finds its assets. The game executable and the game data (NETHERW and CD directory) cannot be in the same location for this to work, because the executable resides in a read-only location in a kind of container.
I have made the game first search the Linux default user locations for config and data files before it falls back to searching in the executable directory.

As a follow-up I would like to overhaul how the game does file and configuration handling in general by writing classes for that. There is too much C-style buffer handling going on all over the place.

It would be great if you could check what a default config location on Windows could be. I was thinking of "$HOME/AppData/Local". Otherwise we could also just keep the next-to-the-executable approach on Windows.

Cheers,
Sebastian

**Comment by GrimSqueaker** [comment]
Here is the comparison to the merging-help branch: https://github.com/turican0/remc2/compare/merging-help...GrimSqueaker:remc2:feature/flatpak

For building the flatpak the `build.sh` script in the flatpak directory can be used.
Running the flatpak is done via
```
flatpak run com.github.thobbsinteractive.magic-carpet-2-hd 
```

**Comment by GrimSqueaker** [comment]
Hi @thobbsinteractive, Hi @turican0,
I am using C++17 features (std::filesystem) which make the Windows build fail at the moment. Could one of you please convert the solution from VS 2017 15.0 to VS 2017 15.7? Then it should also work on Windows.

**Comment by thobbsinteractive** [comment]
I believe I tried setting it to C++ 17 before and on of the depended
libraries was not compatible

**Comment by GrimSqueaker** [comment]
Oh, that would be bad. On Linux I had it on C++17 all the time. So I guess there is no fundamental problem. Maybe those libs need to be updated?

**Comment by thobbsinteractive** [comment]
It is worth trying again for sure. But at the moment I am trying to fix the
viewport code in the latest pull request.
