### ISSUE TITLE
LINUX-FIXME

### ISSUE THREAD

**Issue by turican0** [GrimSqueaker/remc2#22]
I fix some FIXME for linux(at turican0/remc2 development branch now).
Please test it in linux.
When fix is ok, please delete commented FIXME lines.
To other FIXME I add stops for next analyse(In levels with this code).
Tom.

**Comment by GrimSqueaker** [comment]
All your changes are ok and I have removed the "FIXME-OK" comments

**Comment by turican0** [comment]
Next one linux FIXME I fix with TMAPS00TAB_BEGIN_BUFFER rewriting, please remove comments, when fix is ok,
Tom.

**Comment by GrimSqueaker** [comment]
Closing this ticket. The Linux build is working and playable in 32 as well as 64 bit. Any further problems are treated as bugs and get their own ticket.
