### ISSUE TITLE
save game name rendered in wrong place

### ISSUE THREAD

**Issue by GrimSqueaker** [GrimSqueaker/remc2#25]
Maybe this is related to issue https://github.com/GrimSqueaker/remc2/issues/20

When using the load game scroll in the level selection, after clicking on a save game in the list the name is rendered in the middle of the screen. When hovering over the list it renders the missing entry in the correct location. When closing the scroll, the name flows out to the left.
![Screenshot from 2021-02-03 00-04-06](https://user-images.githubusercontent.com/26384847/106675183-f1317100-65b4-11eb-8207-f36017c51597.jpg)

**Comment by turican0** [comment]
This bug in last commit? On my PC drawing is ok. When bug still exist, on your pc, in my last commit, please compare running sub_780F0_load_game_dialog with stable version.
You can insert VGA_Debug_Blit(640, 480, pdwScreenBuffer); to some places and find position in code with bad drawing. 
![image](https://user-images.githubusercontent.com/41465132/106779900-b9bfd480-6647-11eb-9c0a-1c9f3441424a.png)

**Comment by GrimSqueaker** [comment]
Fixed and cleaned up sub_780F0_load_game_dialog a bit.
