### ISSUE TITLE
64bit version crashes in first cave level (level 4)

### ISSUE THREAD

**Issue by GrimSqueaker** [GrimSqueaker/remc2#77]
In `sub_8F100_sound_prod19` the function `sub_938C0_AIL_set_sample_file` is called with an illegal sound buffer pointer (`a2` is `68` in `str_E37A0_sound_buffer2->str_8.wavs_10[a2].dword_0` but `wavs_10` has only 64 entries.

**Comment by GrimSqueaker** [comment]
This is triggered before the crash:
`FIXME: 64bit @ function Convert_to_shadow_D41A0_BYTESTR_0, line 3867, file ../../remc2/engine/Basic.cpp`

**Comment by turican0** [comment]
fixed - number of sound changed from 64 to 96
